#include <string>
#include <vector>

std::vector<std::wstring> some_quotes{
    L"The only people who never fail are those who never try. [Ilka Chase]",
    L"Failure is just another way to learn how to do something right. [Marian Wright Edelman]",
    L"I failed my way to success. [Thomas Edison]",
    L"Every failure brings with it the seed of an equivalent success. [Napoleon Hill]",
    L"Only those who dare to fail greatly can ever achieve greatly. [John F. Kennedy]",
    L"It is hard to fail, but it is worse never to have tried to succeed. [Theodore Roosevelt]",
    L"Imagination is more important than knowledge. [Albert Einstein]",
    L"Hold fast to dreams, for if dreams die, life is a broken winged bird that cannot fly. [Langston Hughes]",
    L"The future belongs to those who believe in the beauty of their dreams. [Eleanor Roosevelt]",
    L"Go confidently in the direction of your dreams. Live the life you have imagined. [Henry David Thoreau]",
    L"You cannot depend on your eyes when your imagination is out of focus. [Mark Twain]",
    L"Commitment leads to action. Action brings your dream closer. [Marcia Wieder]",
    L"I never think of the future [it comes soon enough.]",
    L"Don't waste your life in doubts and fears: Spend yourself on the work before you, well assured that the right performance of this hour's duties will be the best preparation for the hours or ages that follow it. [Ralph Waldo Emerson]",
    L"Do not anticipate trouble or worry about what may never happen. Keep in the sunlight. [Benjamin Franklin]",
    L"Take time to deliberate; but when the time for action arrives, stop thinking and go in. [Andrew Jackson]",
    L"The mind that is anxious about future events is miserable. [Seneca]",
    L"Live in each season as it passes; breathe the air, drink the drink, taste the fruit, and resign yourself to the influences of each. [Henry David Thoreau]",
    L"The art of leadership is saying no, not yes. It is very easy to say yes. [Tony Blair]",
    L"A leader is a dealer in hope. [Napoleon Bonaparte]",
    L"While a good leader sustains momentum, a great leader increases it. [John C. Maxwell]",
    L"A general is just as good or just as bad as the troops under his command make him. [General Douglas MacArthur]",
    L"To do great things is difficult; but to command great things is more difficult. [Friedrich Nietzsche]",
    L"Leadership does not always wear the harness of compromise. [Woodrow Wilson]",
    L"Business opportunities are like buses [there's always another one coming.]",
    L"I avoid looking forward or backward, and try to keep looking upward. [Charlotte Bronte]",
    L"The more difficulties one has to encounter, within and without, the more significant and the higher in inspiration his life will be. [Horace Bushnell]",
    L"Every artist was first an amateur. [Ralph Waldo Emerson]",
    L"I was always looking outside myself for strength and confidence, but it comes from within. It is there all of the time. [Anna Freud]",
    L"We can do anything we want to do if we stick to it long enough. [Helen Keller]",
    L"Our business in life is not to get ahead of others, but to get ahead of ourselves. [E. Joseph Cossman]",
    L"Insist on yourself. Never imitate. [Ralph Waldo Emerson]",
    L"Who looks outside, dreams. Who looks inside, awakes. [Carl Jung]",
    L"It is not easy to find happiness in ourselves, and it is not possible to find it elsewhere. [Agnes Repplier]",
    L"The only journey is the one within. [Rainer Maria Rilke]",
    L"Follow your honest convictions, and stay strong. [William Thackeray]",
    L"The happiness of your life depends upon the quality of your thoughts; therefore guard accordingly. [Marcus Aurelius]",
    L"Action may not always bring happiness; but there is no happiness without action. [Benjamin Disraeli]",
    L"Happiness depends more on the inward disposition of mind than on outward circumstances. [Benjamin Franklin]",
    L"There is no happiness except in the realization that we have accomplished something. [Henry Ford]",
    L"Happiness is not a goal, but a by-product. [Eleanor Roosevelt]",
    L"Happiness is not a state to arrive at, but a manner of traveling. [Margaret Lee Runbeck]",
    L"Purpose is what gives life a meaning. [C. H. Parkhurst]",
    L"The significance of a man is not in what he attains but in what he longs to attain. [Kahlil Gibran]",
    L"In all things that you do, consider the end. [Solon]",
    L"Life can be pulled by goals just as surely as it can be pushed by drives. [Viktor Frankl]",
    L"The virtue lies in the struggle, not in the prize. [Richard Monckton Milnes]",
    L"To reach a port, we must sail [sail, not tie at anchor]",
    L"Success is the child of audacity. [Benjamin Disraeli]",
    L"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. [Vince Lombardi]",
    L"The secret of success is to know something nobody else knows. [Aristotle Onassis]",
    L"The surest way not to fail is to determine to succeed. [Richard Brinsley Sheridan]",
    L"I cannot give you the formula for success, but I can give you the formula for failure [which is: Try to please everybody.]",
    L"Careful thinking and hard work will solve nearly all your problems. Try and see for yourself. [Ullery]",
    L"Years teach us more than books. [Berthold Auerbach]",
    L"The only medicine for suffering, crime, and all the other woes of mankind, is wisdom. [Thomas Huxley]",
    L"The art of being wise is knowing what to overlook. [William James]",
    L"The great lesson is that the sacred is in the ordinary, that it is to be found in one's daily life, in one's neighbors, friends and family, in one's backyard. [Abraham Maslow]",
    L"A wise man learns by the mistakes of others, a fool by his own. [Latin proverb]",
    L"No man was ever wise by chance. [Seneca]",
    L"In everything the ends well defined are the secret of durable success. [Victor Cousins]",
    L"Arriving at one goal is the starting point to another. [John Dewey]",
    L"A goal is a dream with a deadline. [Napoleon Hill]",
    L"Most 'impossible' goals can be met simply by breaking them down into bite-size chunks, writing them down, believing them, and then going full speed ahead as if they were routine. [Don Lancaster]",
    L"Goals are the fuel in the furnace of achievement. [Brian Tracy]",
    L"We are what we repeatedly do. Excellence, therefore, is not an act but a habit. [Aristotle]",
    L"Take risks and you'll get the payoffs. Learn from your mistakes until you succeed. It's that simple. [Bobby Flay]",
    L"The best way out is always through. [Robert Frost]",
    L"You miss 100 percent of the shots you don't take. [Wayne Gretzky]",
    L"Nothing will ever be attempted if all possible objections must first be overcome. [Samuel Johnson]",
    L"Don't bunt. Aim out of the ballpark. [David Ogilvy]",
    L"The critical ingredient is getting off your butt and doing something. It’s as simple as that. A lot of people have ideas, but there are few who decide to do something about them now. Not tomorrow. Not next week. But today. The true entrepreneur is a doer, not a dreamer. [Nolan Bushnell, entrepreneur.]",
    L"Never give in [never, never, never, never, in nothing great or small, large or petty, never give in except to convictions of honour and good sense. Never yield to force; never yield to the apparently overwhelming might of the enemy. - Winston Churchill, British Prime Minister.]",
    L"Your most unhappy customers are your greatest source of learning. [Bill Gates, co-founder of Microsoft.]",
    L"I have not failed. I’ve just found 10,000 ways that won’t work. [Thomas Edison, inventor.]",
    L"Entrepreneurship is neither a science nor an art. It is a practice. [Peter Drucker, management consultant, educator, and author.]",
    L"In the modern world of business, it is useless to be a creative, original thinker unless you can also sell what you create. [David Ogilvy, Co-founder of Ogilvy & Mather.]",
    L"Success is how high you bounce after you hit bottom. [General George Patton.]",
    L"If you’re not embarrassed by the first version of your product, you’ve launched too late. [Reid Hoffman, co-founder of LinkedIn.]",
    L"Positive thinking will let you do everything better than negative thinking will. [Zig Ziglar, author, salesman, and motivational speaker.]",
    L"I’m not afraid of dying, I’m afraid of not trying. [Jay Z, musician.]",
    L"Whatever the mind can conceive and believe, the mind can achieve. [Dr. Napoleon Hill, author of Think and Grow Rich.]",
    L"The longer you’re not taking action the more money you’re losing [Carrie Wilkerson]",
    L"If you live for weekends or vacations, your shit is broken [Gary Vaynerchuk]",
    L"Go Big, or Go Home [Eliza Dushku]",
    L"Most great people have attained their greatest success just one step beyond their greatest failure [Napoleon Hill]",
    L"Opportunity is missed by most people because it is dressed in overalls and looks like work [Thomas Edison]",
    L"Have the end in mind and every day make sure your working towards it [Ryan Allis]",
    L"He who begins many things finishes but few [German Proverb]",
    L"The best use of life is to spend it for something that outlasts it [William James]",
    L"If you think education is expensive, try ignorance [Derek Bok]",
    L"Entrepreneurship is living a few years of your life like most people wont so you can spend the rest of your life like most people can’t [A student in Warren G. Tracy’s class]",
    L"Lend your friend $20, if he doesn’t pay you back then he’s not your friend. Money well spent [Ted Nicolas]",
    L"Be nice to geek’s, you’ll probably end up working for one [Bill Gates]",
    L"To never forget that the most important thing in life is the quality of life we lead [Quoted by Tony Hsieh on Retireat21]",
    L"Its better to own the racecourse then the race horse [Unknown]",
    L"When you go to buy, don’t show your silver [Chinese Proverb]",
    L"It’s easier to ask forgiveness than it is to get permission [Grace Hopper]",
    L"To win without risk is to triumph without glory [Corneille]",
    L"Example is not the main thing in influencing other people; it’s the only thing [Abraham Lincoln]",
    L"Associate yourself with people of good quality, for it is better to be alone than in bad company [Booker T. Washington]",
    L"Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great [Mark Twain]",
    L"There is only one success [to be able to spend your life in your own way]",
    L"You don’t buy a nice car and get rich you get rich and buy a nice car [Unknown]",
    L"Fall seven times, stand up eight [Japanese Proverb]",
    L"One day your life will flash before your eyes. Make sure it is worth watching [Mooie]",
    L"Whatever the mind can conceive and believe, the mind can achieve [Dr. Napoleon Hill]",
    L"I have not failed. I’ve just found 10,000 ways that won’t work [Thomas Alva Edison]",
    L"If you ain’t making waves, you ain’t kickin’ hard enough [Unknown]",
    L"What is not started will never get finished [Johann Wolfgang von Goethe]",
    L"Do not wait to strike until the iron is hot; but make it hot by striking [William B. Sprague]",
    L"When you cease to dream you cease to live [Malcolm Forbes]",
    L"There are two rules for success. 1) Never tell everything you know. [Roger H. Lincoln]",
    L"The only place where success comes before work is in the dictionary. [Vidal Sassoon]",
    L"Every single person I know who is successful at what they do is successful because they love doing it. [Joe Penna]",
    L"Being realistic is the most commonly traveled road to mediocrity. [Will Smith]",
    L"Whenever an individual or a business decides that success has been attained, progress stops. [Thomas J. Watson]",
    L"To be successful, you have to have your heart in your business, and your business in your heart. [Thomas J. Watson]",
    L"If hard work is the key to success, most people would rather pick the lock. [Claude McDonald]",
    L"Success is simply a matter of luck. Ask any failure. [Earl Wilson]",
    L"The road to success is always under construction. [Arnold Palmer]",
    L"Anything the mind can conceive and believe, it can achieve. [Napoleon Hill]",
    L"Most great people have attained their greatest success just one step beyond their greatest failure. [Napoleon Hill]",
    L"Whether you think you can or you can’t, you’re right. [Henry Ford]",
    L"Failure defeats losers, failure inspires winners. [Robert T. Kiyosaki]",
    L"I have not failed. I’ve just found 10,000 ways that won’t work. [Thomas Edison]",
    L"The biggest failure you can have in life is not trying at all. [Emil Motycka]",
    L"I honestly think it is better to be a failure at something you love than to be a success at something you hate. [George Burns]",
    L"Leaders don’t force people to follow, they invite them on a journey. [Charles S. Lauer]",
    L"Example is not the main thing in influencing other people; it’s the only thing. [Abraham Lincoln]",
    L"Leadership is doing what is right when no one is watching. [George Van Valkenburg]",
    L"Leadership is the art of getting someone else to do something you want done because he wants to do it. [Dwight D. Eisenhower]",
    L"The difference between a boss and a leader: a boss says, ‘Go!’ -a leader says, ‘Let’s go!’. [E. M. Kelly]",
    L"I am more afraid of an army of one hundred sheep led by a lion than an army of one hundred lions led by a sheep. [Charles Maurice]",
    L"The whole problem with the world is that fools and fanatics are always so certain of themselves, but wiser people so full of doubts. [Bertrand Russell]",
    L"We are what we repeatedly do. Excellence, then, is not an act, but a habit. [Aristotle]",
    L"Cannibals prefer those who have no spines. [Stanislaw Lem]",
    L"A ship in harbor is safe. But that’s now what ships are built for. [William Shedd]",
    L"If one does not know to which port one is sailing, no wind is favorable. [Lucius Annaeus Seneca]",
    L"You miss 100% of the shots you don’t take. [Wayne Gretzky]",
    L"I’m not a businessman. I’m a business, man. [Jay-Z]",
    L"The vision must be followed by the venture. It is not enough to stare up the steps – we must step up the stairs. [Vance Hayner]",
    L"Do not wait to strike until the iron is hot; but make it hot by striking. [William B. Sprague]",
    L"It’s easier to ask forgiveness than it is to get permission. [Grace Hopper]",
    L"Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do. [Mark Twain]",
    L"One day your life will flash before your eyes. Make sure it is worth watching. [Mooie]",
    L"“I think it’s wrong that only one company makes the game Monopoly. [Steven Wright]",
    L"Ever notice how it’s a penny for your thoughts, yet you put in your two-cents? Someone is making a penny on the deal. [Steven Wright]",
    L"Catch a man a fish, and you can sell it to him. Teach a man to fish, and you ruin a wonderful business opportunity. [Karl (maybe Groucho) Marx]",
    L"I used to sell furniture for a living. The trouble was, it was my own. [Les Dawson]",
    L"Marking dynamos for repair $10,000.00—2 hours labor $10.00; knowing where to mark $9,990.00. [Invoice from Charles Steinmetz]",
    L"By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day. [Robert Frost]",
    L"My son is now an ‘entrepreneur’. That’s what you’re called when you don’t have a job. [Ted Turner]",
    L"I didn’t go to college, but if I did, I would’ve taken all my tests at a restaurant, ’cause ‘The customer is always right.’ [Mitch Hedberg]",
    L"Formal education will make you a living. Self education will make you a fortune. [Jim Rohn]",
    L"The greatest reward in becoming a millionaire is not the amount of money that you earn. It is the kind of person that you have to become to become a millionaire in the first place. [Jim Rohn]",
    L"If you’re not learning while you’re earning, you’re cheating yourself out of the better portion of your compensation. [Napoleon Hill]",
    L"A business that makes nothing but money is a poor business. [Henry Ford]",
    L"After a certain point, money is meaningless. It ceases to be the goal. The game is what counts. [Aristotle]",
    L"I treat business a bit like a computer game. I count money as points. I’m doing really well: making lots of money and lots of points. [Michael Dunlop]",
    L"All of my friends were doing babysitting jobs. I wanted money without the job. [Adam Horwitz]",
    L"“I don’t pay good wages because I have a lot of money; I have a lot of money because I pay good wages. [Robert Bosch]",
    L"Lend your friend $20. If he doesn’t pay you back then he’s not your friend. Money well spent. [Ted Nicolas]",
    L"Money and success don’t change people; they merely amplify what is already there. [Will Smith]",
    L"The secret of getting ahead is getting started. [Agatha Christie]",
    L"Hire character. Train skill. [Peter Schultz]",
    L"In preparing for battle I have always found that plans are useless, but planning is indispensable. [Dwight D. Eisenhower]",
    L"You’ve got to stop doing all the things that people have tried, tested, and found out don’t work. [Michael Dunlop]",
    L"I never perfected an invention that I did not think about in terms of the service it might give others… I find out what the world needs, then I proceed to invent. [Thomas Edison]",
    L"If you’re not making mistakes, then you’re not making decisions. [Catherine Cook]",
    L"Your most unhappy customers are your greatest source of learning. [Bill Gates]",
    L"One can get anything if he is willing to help enough others get what they want. [Zig Ziglar]",
    L"An entrepreneur tends to bite off a little more than he can chew hoping he’ll quickly learn how to chew it. [Roy Ash]",
    L"The true entrepreneur is a doer, not a dreamer. [Nolan Bushnell]",
    L"Whenever you are asked if you can do a job, tell ’em, ‘Certainly, I can!’ Then get busy and find out how to do it. [Theodore Roosevelt]",
    L"Everything started as nothing. [Ben Weissenstein]",
    L"If you start with nothing and end up with nothing, there’s nothing lost. [Michael Dunlop]",
    L"Start today, not tomorrow. If anything, you should have started yesterday. [Emil Motycka]",
    L"Make it happen now, not tomorrow. Tomorrow is a loser’s excuse. [Andrew Fashion]",
    L"Every day I get up and look through the Forbes list of the richest people in America. If I’m not there, I go to work. [Robert Orben]",
    L"Entrepreneurship is living a few years of your life like most people won’t, so that you can spend the rest of your life like most people can’t. [Anonymous]",
    L"Yesterday’s home runs don’t win today’s games. [Babe Ruth]",
    L"You should always stay hungry. Stay hungry, so you can eat. [Syed Balkhi]",
    L"If you’re not living life on the edge, you’re taking up too much space. [Anonymous]",
    L"I wasn’t satisfied just to earn a good living. I was looking to make a statement. [Donald Trump]",
    L"Opportunity is missed by most people because it is dressed in overalls and looks like work. [Thomas Edison]",
    L"You must either modify your dreams or magnify your skills. [Jim Rohn]",
    L"Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great. [Mark Twain]",
    L"Not a single person whose name is worth remembering lived a life of ease. [Ryan P. Allis]",
    L"If you think that you are going to love something, give it a try. You’re going to kick yourself in the butt for the rest of your life if you don’t. [Joe Penna]",
    L"The best time to plant a tree is twenty years ago. The second best time is now. [Chinese Proverb]",
    L"If you want one year of prosperity, grow grain. If you want ten years of prosperity, grow trees. If you want one hundred years of prosperity, grow people. [Chinese Proverb]",
    L"Vision without action is a daydream. Action without vision is a nightmare. [Japanese Proverb]",
    L"Sow a thought, reap an action; sow an action, reap a habit; sow a habit, reap a character; sow a character, reap a destiny. [Chinese Proverb]",
    L"A bad workman blames his tools. [Chinese Proverb]",
    L"A fall into a ditch makes you wiser. [Chinese Proverb]",
    L"Defeat isn’t bitter if you don’t swallow it. [Chinese Proverb]",
    L"The diamond cannot be polished without friction, nor the man perfected without trials. [Chinese Proverb]",
    L"A jade stone is useless before it is processed; a man is good-for-nothing until he is educated. [Chinese Proverb]",
    L"A journey of a thousand miles begins with a single step. [Chinese Proverb]",
    L"The loftiest towers rise from the ground. [Chinese Proverb]",
    L"Building a castle is difficult. Defending and maintaining it is harder still. [Asian Proverb]",
    L"A person who says it cannot be done should not interrupt the man doing it. [Chinese Proverb]",
    L"All cats love fish but fear to wet their paws. [Chinese Proverb]",
    L"Don’t stand by the water and long for fish; go home and weave a net. [Chinese Proverb]",
    L"Everyone should carefully observe which way his heart draws him, and then choose that way with all his strength. [Hasidic Proverb]",
    L"Failing to plan is planning to fail. [Chinese Proverb]",
    L"If you pay peanuts, you get monkeys. [Chinese Proverb]",
    L"Make happy those who are near, and those who are far will come. [Chinese Proverb]",
    L"Teachers open the door. You enter by yourself. [Chinese Proverb]",
    L"Find a job you love and you’ll never work a day in your life. [Confucius]",
    L"The entrepreneur builds an enterprise; the technician builds a job. [Michael Gerber]",
    L"If you want to be inventive [you have to be willing to fail.”]",
    L"The challenge is not just to build a company that can endure; but to build one that is worthy of enduring. [Jim Collins]",
    L"Success is a lousy teacher. It seduces smart people into thinking they can’t lose. [Bill Gates]",
    L"Don’t treat your customers like a bunch of purses and wallets. [Chris Brogan]",
    L"Nine out of ten businesses fail; so I came up with a foolproof plan [create ten businesses.”]",
    L"I’m not a businessman [I”m a business, man.”]",
    L"If plan ‘A’ fails [remember you have 25 letters left.”]",
    L"We make a living by what we get. But we make a life by what we give. [Winston Churchhill]",
    L"Believe that you will succeed [and you will.”]",
    L"Victory comes only after many struggles and countless defeats. [Og Mandino]",
    L"As long as you’re going to be thinking anyway, think big. [Donald Trump]",
    L"Success is how high you bounce after you hit bottom [General George Patton]",
    L"Remembering you are going to die is the best way I know to avoid the trap of thinking you have something to lose. [Steve Jobs]",
    L"It’s not about how to get started; its about how to get noticed. [Steve Case]",
    L"A ship in harbor is safe, but that’s not what ships are for. [John Shedd]",
    L"If I find 10,000 ways something won’t work, I haven’t failed. I am not discouraged, because every wrong attempt discarded is often a step forward. [Thomas Edison]",
    L"Business opportunities are like buses, there’s always another one coming. [Richard Branson]",
    L"If we don’t allow ourselves to make mistakes, we will never invest in things that are radical. [Jeff Clavier]",
    L"The critical ingredient is getting off your butt and doing something. [Nolan Bushnell]",
    L"Nothing will work unless you do. [Maya Angelou]",
    L"Try not to be a man of success, but rather try to become a man of value. [Albert Einstein]",
    L"You won’t get anything unless you have the vision to imagine it. [John Lennon]",
    L"A man must be big enough to admit his mistakes, smart enough to profit from them, and strong enough to correct them. [John C. Maxwell]",
    L"In the modern world of business, it is useless to be a creative, original thinker unless you can also sell what you create. [David Ogilvy]",
    L"Success is doing what you want, where you want, when you want, with whom you want as much as you want. [Tony Robbins]",
    L"If you don’t have a competitive advantage [don’t compete.”]",
    L"You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win. [Zig Ziglar]",
    L"If everything seems under control, you’re just not going fast enough. [Mario Andretti]",
    L"Don’t be trapped by dogma [which is living with the results of other people’s thinking.”]",
    L"Do or do not. There is no try. [Yoda]",
    L"Show me a person who never made a mistake, and I will show you a person who never did anything. [William Rosenberg, founder of Dunkin’ Donuts]",
    L"Ideas are commodity. Execution of them is not. [Michael Dell, CEO of Dell]",
    L"User experience is everything. It always has been, but it’s undervalued and underinvested in. If you don’t know user-centered design, study it. Hire people who know it. Obsess over it. Live and breathe it. Get your whole company on board. [Evan Williams, co-founder of Twitter]",
    L"A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty. [Winston Churchill, British Prime Minister]",
    L"The man who does not work for the love of work but only for money is likely to neither make money nor find much fun in life. [Charles M. Schwab, American steel magnate]",
    L"Be undeniably good. No marketing effort or social media buzzword can be a substitute for that. [Anthony Volodkin, founder of Hype Machine]",
    L"Ideas are easy. Implementation is hard. [Guy Kawasaki, founder of AllTop]",
    L"You can say anything to anyone, but how you say it will determine how they will react. [John Rampton, entrepreneur and investor]",
    L"Always deliver more than expected. [Larry Page, co-founder of Google]",
    L"Assume you have 90 seconds with a new user before they decide to use your app or delete it. [Tamara Steffens, Acompli]",
    L"Even if you don’t have the perfect idea to begin with, you can likely adapt. [Victoria Ransom, co-founder of Wildfire Interactive]",
    L"Make your team feel respected, empowered and genuinely excited about the company’s mission. [Tim Westergen, founder of Pandora]",
    L"Stay self-funded as long as possible. [Garrett Camp, co-founder of Stumbleupon]",
    L"In between goals is a thing called life, that has to be lived and enjoyed. [Sid Caesar, Entertainer]",
    L"Wonder what your customer really wants? Ask. Don’t tell. [Lisa Stone, co-founder of BlogHer]",
    L"When times are bad is when the real entrepreneurs emerge. [Robert Kiyosaki, author of Rich Dad Poor Dad]",
    L"What do you need to start a business? Three simple things: know your product better than anyone, know your customer, and have a burning desire to succeed. [Dave Thomas, founder of Wendy’s]",
    L"Get big quietly, so you don’t tip off potential competitors. [Chris Dixon, co-founder of Hunch]",
    L"Don’t worry about failure; you only have to be right once. [Drew Houston, founder of Dropbox]",
    L"Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma [which is living with the results of other people’s thinking. Don’t let the noise of other’s opinions drown out your own inner voice. And most important, have the courage to follow your heart and intuition. They somehow already know what you truly want to become. Everything else is secondary.”]",
    L"Don’t be cocky. Don’t be flashy. There’s always someone better than you. [Tony Hsieh, Zappos.com CEO]",
    L"Don’t take too much advice. Most people who have a lot of advice to give — with a few exceptions — generalize whatever they did. Don’t over-analyze everything. I myself have been guilty of over-thinking problems. Just build things and find out if they work. [Ben Silbermann, co-founder of Pinterest]",
    L"Openly share and talk to people about your idea. Use their lack of interest or doubt to fuel your motivation to make it happen. [Todd Garland, founder of BuySellAds]",
    L"How you climb a mountain is more important than reaching the top. [Yvon Chouinard, founder of Patagonia]",
    L"Associate yourself with people of good quality, for it is better to be alone than in bad company. [Booker T. Washington, Educator and author]",
    L"It’s fine to celebrate success but it is more important to heed the lessons of failure. [Bill Gates, co-founder of Microsoft]",
    L"It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you’ll do things differently. [Warren Buffett, Investor]",
    L"Statistics suggest that when customers complain, business owners and managers ought to get excited about it. The complaining customer represents a huge opportunity for more business. [Zig Ziglar, author and motivational speaker]",
    L"There is only one success- to be able to spend your life in your own way. [Christopher Morley, journalist]",
    L"Formal education will make you a living; self-education will make you a fortune. [Jim Rohn, author and speaker]",
    L"When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. [Henry Ford, founder of Ford Motor Company]",
    L"Rarely have I seen a situation where doing less than the other guy is a good strategy. [Jimmy Spithill, Australian yachtsman]",
    L"You miss 100 percent of the shots you don’t take. [Wayne Gretzky, NHL Hall of Famer]",
    L"The best time to plant a tree was 20 years ago. The second best time is now. [Chinese proverb]",
    L"The secret to successful hiring is this: look for the people who want to change the world. [Marc Benioff, CEO of Salesforce]",
    L"Twenty years from now, you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover. [Mark Twain, author]",
    L"If you’ve got an idea, start today. There’s no better time than now to get going. That doesn’t mean quit your job and jump into your idea 100% from day one, but there’s always small progress that can be made to start the movement. [Kevin Systrom, co-founder of Instagram]",
    L"It’s almost always harder to raise capital than you thought it would be, and it always takes longer. So plan for that. [Richard Harroch, Venture Capitalist]",
    L"For all of the most important things, the timing always sucks. Waiting for a good time to quit your job? The stars will never align and the traffic lights of life will never all be green at the same time. The universe doesn’t conspire against you, but it doesn’t go out of its way to line up the pins either. Conditions are never perfect. “Someday is a disease that will take your dreams to the grave with you. Pro and con lists are just as bad. If it’s important to you and you want to do it “eventually, just do it and correct course along the way. [Timothy Ferriss, author of The 4-Hour Work Week]",
    L"I don’t have big ideas. I sometimes have small ideas, which seem to work out. [Matt Mullenweg, founder of Automattic]",
    L"Fail often so you can succeed sooner. [Tom Kelley, Ideo partner]",
    L"When you cease to dream you cease to live. [Malcolm Forbes, chairman and editor in chief of Forbes Magazine]",
    L"Whatever the mind can conceive and believe, the mind can achieve. [Dr. Napoleon Hill, author of Think and Grow Rich]",
    L"Running a start-up is like eating glass. You just start to like the taste of your own blood. [Sean Parker, co-founder of Napster]",
    L"My number one piece of advice is: you should learn how to program. [Mark Zuckerberg, founder of Facebook]",
    L"The way to get started is to quit talking and begin doing. [Walt Disney, co-founder of the Walt Disney Company]",
    L"The pace of change for entrepreneurs is rapidly accelerating, and the cost and risk of launching a new business and getting off the ground is just amazing. The ability to gain user feedback really quickly and adapt to what your consumers want is totally different with the web as it is now. But finding a new market, helping people and taking that original idea and turning it into a business is really exciting right now. [Matt Mickiewicz, co-founder of 99 Designs]",
    L"Building and hanging on to an audience is the biggest role of social media. [Matthew Inman, The Oatmeal]",
    L"Every feature has some maintenance cost, and having fewer features lets us focus on the ones we care about and make sure they work very well. [David Karp, founder of Tumblr]",
    L"A poorly implemented feature hurts more than not having it at all. [Noah Everett, founder of Twitpic]",
    L"the entrepreneur always searches for change, responds to it, and exploits it as an opportunity. [Peter F. Drucker, educator and author]",
    L"You don’t learn to walk by following rules. You learn by doing and falling over. [Richard Branson, founder of Virgin Group]",
    L"The fastest way to change yourself is to hang out with people who are already the way you want to be. [Reid Hoffman, co-founder of Linkedin]",
    L"Risk more than others think is safe. Dream more than others think is practical. [Howard Schultz, CEO of Starbucks]",
    L"You shouldn’t focus on why you can’t do something, which is what most people do. You should focus on why perhaps you can, and be one of the exceptions. [Steve Case, co-founder of AOL]",
    L"The critical ingredient is getting off your butt and doing something. It’s as simple as that. A lot of people have ideas, but there are few who decide to do something about them now. Not tomorrow. Not next week. But today. The true entrepreneur is a doer not a dreamer. [Nolan Bushnell, founder of Atari]",
    L"If you cannot do great things, do small things in a great way. [Napoleon Hill, author]",
    L"Success is not what you have, but who you are. [Bo Bennet, author and entreprenuer]",
    L"One of the huge mistakes people make is that they try to force an interest on themselves. You don’t choose your passions; your passions choose you. [Jeff Bezos, founder and CEO of Amazon.com]",
    L"Lots of companies don’t succeed over time. What do they fundamentally do wrong? They usually miss the future. [Larry Page, CEO of Google]",
    L"It takes humility to realize that we don’t know everything, not to rest on our laurels and know that we must keep learning and observing. If we don’t, we can be sure some startup will be there to take our place. [Cher Wang, CEO of HTC]",
    L"There’s an entrepreneur right now, scared to death, making excuses, saying, ‘It’s not the right time just yet.’ There’s no such thing as a good time. Get out of your garage and go take a chance, and start your business. [Kevin Plank, CEO of Under Armour]",
    L"Be really picky with your hiring, and hire the absolute best people you possibly can. People are the most important component of almost every business, and attracting the best talent possible is going to make a huge difference. [Peter Berg, founder of October Three]",
    L"Worry about being better; bigger will take care of itself. Think one customer at a time and take care of each one the best way you can. [Gary Comer, founder of Land’s End]",
    L"You have a viable business only if your product is either better or cheaper than the alternatives. If it’s not one or the other, you might make some money at first, but it’s not a sustainable business. [Jim Koch, founder of Boston Beer Co.]",
    L"Every time I took these bigger risks, the opportunity for a bigger payout was always there. [Casey Neistat, filmmaker]",
    L"If you can do something to get somebody excited — not everybody — but if you can be the best for somebody, then you can win. [Ron Shaich, founder and CEO of Panera Bread]",
    L"Would you like me to give you a formula for success? It’s quite simple, really: Double your rate of failure. You are thinking of failure as the enemy of success. But it isn’t at all. You can be discouraged by failure or you can learn from it, so go ahead and make mistakes. Make all you can. Because remember that’s where you will find success. [Thomas J. Watson, businessman]",
    L"People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy. [Tony Robbins, motivational speaker]",
    L"The only limit to our realization of tomorrow will be our doubts of today. [Franklin D. Roosevelt]",
    L"The successful warrior is the average man, with laser-like focus. [Bruce Lee, actor and martial arts instructor]",
    L"Fall seven times and stand up eight. [Japanese proverb]",
    L"The successful man is the one who finds out what is the matter with his business before his competitors do. [Roy L. Smith, animator and film director]",
    L"There’s no shortage of remarkable ideas, what’s missing is the will to execute them. [Seth Godin, author and speaker]",
    L"Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down. [Charles F. Kettering, inventor]",
    L"A successful man is one who can lay a firm foundation with the bricks others have thrown at him. [David Brinkley, newscaster]",
    L"Everyone is a genius. But if you judge a fish by its ability to climb a tree, it will spend its whole life believing it is stupid. [Albert Einstein, Theoretical Physicist]",
    L"Success in business requires training and discipline and hard work. But if you’re not frightened by these things, the opportunities are just as great today as they ever were. [David Rockefeller, American banker]",
    L"It is never too late to be what you might have been. [George Eliot, journalist and novelist]",
    L"I am not a product of my circumstances. I am a product of my decisions. [Stephen Covey, author and businessman]",
    L"There is only one way to avoid criticism: Do nothing, say nothing, and be nothing. [Aristotle, Greek philosopher]",
    L"Build your own dreams, or someone else will hire you to build theirs. [Farrah Gray, investor and motivational speaker]",
    L"You may be disappointed if you fail, but you are doomed if you don’t try. [Beverly Sills, operatic soprano]",
    L"I learned not to worry so much about the outcome, but to concentrate on the step I was on and to try to do it as perfectly as I could when I was doing it. [Steve Wozniak, Co-Founder of Apple]"};
